services:
  database.lab-project:
    container_name: database
    image: mongo
    restart: always
    environment:
      - MONGO_INITDB_DATABASE=test
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=pass
    ports:
      - "27017:27017"
    volumes:
      - mongodb:/data/db
      - mongoconfig:/data/configdb


volumes:
  mongodb:
  mongoconfig: